// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        int64  `gorm:"column:uid;not null" json:"uid"`
	Province   string `gorm:"column:province;not null" json:"province"`
	City       string `gorm:"column:city;not null" json:"city"`
	UpdateTime int64  `gorm:"column:update_time;not null" json:"update_time"`
	CreateTime int64  `gorm:"column:create_time;not null" json:"create_time"`
	DeleteTime int64  `gorm:"column:delete_time;not null" json:"delete_time"`
}

func (m *Address) IsEmpty() bool {
	if m == nil {
		return true
	}
	return m.ID == 0
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
