version: '3.7'

# docker exec -it redis7001 redis-cli -p 7001 --cluster create 192.168.100.104:7001 192.168.100.104:7002 192.168.100.104:7003 192.168.100.104:7004 192.168.100.104:7005 192.168.100.104:7006 --cluster-replicas 1

volumes:
  redis7001:
  redis7002:
  redis7003:
  redis7004:
  redis7005:
  redis7006:

networks:
  custom_net:
    external: true

services:
  redis7001:
    image: 'redis'
    container_name: redis7001
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-cluster/7001.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
      - "17001:17001"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    networks:
      custom_net:          # 使用指定的网络 backend, 并且设置网络别名为 test1，
        aliases:        # 设置网络别名后，可以在其他容器中 ping test1 访问到该容器
          - redis7001
#        ipv4_address: 172.18.0.100

  redis7002:
    image: 'redis'
    container_name: redis7002
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-cluster/7002.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
      - "17002:17002"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    networks:
      custom_net:          # 使用指定的网络 backend, 并且设置网络别名为 test1，
        aliases:        # 设置网络别名后，可以在其他容器中 ping test1 访问到该容器
          - redis7002
#        ipv4_address: 172.18.0.101

  redis7003:
    image: 'redis'
    container_name: redis7003
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-cluster/7003.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
      - "17003:17003"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    networks:
      custom_net:          # 使用指定的网络 backend, 并且设置网络别名为 test1，
        aliases:        # 设置网络别名后，可以在其他容器中 ping test1 访问到该容器
          - redis7003
#        ipv4_address: 172.18.0.102

  redis7004:
    image: 'redis'
    container_name: redis7004
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-cluster/7004.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
      - "17004:17004"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    networks:
      custom_net:          # 使用指定的网络 backend, 并且设置网络别名为 test1，
        aliases:        # 设置网络别名后，可以在其他容器中 ping test1 访问到该容器
          - redis7004
#        ipv4_address: 172.18.0.103

  redis7005:
    image: 'redis'
    container_name: redis7005
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-cluster/7005.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
      - "17005:17005"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    networks:
      custom_net:          # 使用指定的网络 backend, 并且设置网络别名为 test1，
        aliases:        # 设置网络别名后，可以在其他容器中 ping test1 访问到该容器
          - redis7005
#        ipv4_address: 172.18.0.104

  redis7006:
    image: 'redis'
    container_name: redis7006
    command:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis-cluster/7006.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "7006:7006"
      - "17006:17006"
    environment:
      # 设置时区为上海，否则时间会有问题
      - TZ=Asia/Shanghai
    networks:
      custom_net:          # 使用指定的网络 backend, 并且设置网络别名为 test1，
        aliases:        # 设置网络别名后，可以在其他容器中 ping test1 访问到该容器
          - redis7006
#        ipv4_address: 172.18.0.105
