version: '3'

services:

  redis:
    image: redis
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - './redis/redis.conf:/etc/redis.conf:cached'
    command: redis-server /etc/redis.conf --appendonly yes
    ports:
      - '6379:6379'     #主机端口: 容器端口

